name: Lint Terraform Module Documentation

description: A composite action for linting Terraform module documentation.

inputs:
  terraform-docs-version:
    description: The version of terraform-docs to use.
    default: 0.24.0
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup terraform-docs
      run: ${{ github.action_path }}/src/setup_terraform_docs.sh
      shell: sh
      env:
        TERRAFORM_DOCS_VERSION: ${{ inputs.terraform-docs-version }}

    - name: Configure terraform-docs
      run: ${{ github.action_path }}/src/emit_terraform_docs_yml.sh
      shell: sh

    - name: Lint Terraform Module Documentation
      run: |-
        terraform-docs --output-check .
      shell: sh
